apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "tp-doc-test1"
  description: "this is a test doc"
  annotations:
    github.com/project-slug: ttpp8794/tp-bs-doc1
    backstage.io/techdocs-ref: dir:.
spec:
  type: documentation
  lifecycle: experimental
  owner: "Tao Peng"
